name: github-runner

services:
  github-runner:
    image: kerklangsi/github-runner:latest
    container_name: github-runner-manager
    restart: unless-stopped
    network_mode: bridge
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /DATA/AppData/github-runner/data
        target: /app/data
      - type: bind
        source: /DATA/AppData/github-runner/runner
        target: /opt/github-runner
      - type: bind
        source: /DATA/AppData/github-runner/shared_data
        target: /opt/shared_data
      - type: bind
        source: /DATA/AppData/github-runner/cache
        target: /home/runner/.cache
